version: '3'
services:
    vpn:
        image: thrnz/docker-wireguard-pia
        hostname: torrents
        volumes:
            # Auth token is stored here
            - /srv/datastore/docker/piawireguard/pia:/pia
            # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
            - /srv/datastore/docker/piawireguard/pia-shared:/pia-shared
        cap_add:
            - NET_ADMIN
            # SYS_MODULE might not be needed with a 5.6+ kernel?
            - SYS_MODULE
        # Mounting the tun device may be necessary for userspace implementations
        devices:
          - /dev/net/tun:/dev/net/tun
        container_name: piawireguard
        environment:
            # The following env vars are required:
            - LOC=ca_toronto
            - USER=p9798466
            - PASS=nnEmPHTZ84
            # The rest are optional:
            - LOCAL_NETWORK=10.10.0.0/16
            #- KEEPALIVE=25
            #- VPNDNS=8.8.8.8,8.8.4.4
            - PORT_FORWARDING=1
            #- WG_USERSPACE=1
        sysctls:
            # wg-quick fails to set this without --privileged, so set it here instead if needed
            - net.ipv4.conf.all.src_valid_mark=1
            # May as well disable ipv6. Should be blocked anyway.
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
        # The container has no recovery logic. Use a healthcheck to catch disconnects.
        healthcheck:
            test: ping -c 1 www.google.com || exit 1
            interval: 30s
            timeout: 10s
            retries: 3

        networks:
          MyMacvlan:
            ipv4_address: 10.10.20.80

        restart: unless-stopped

networks:
  MyMacvlan:
    external: true
    name: MyMacvlan
